---
- hosts: centos
  user: root

  tasks:
    - name: Update CentOS
      command: bash -c "yum -y update"

    - name: EPEL install
      yum: name={{item}} state=latest
      with_items:
      - epel-release

    - name: Software install
      yum: name={{item}} state=latest
      with_items:
      - qemu-kvm
      - libvirt
      - libvirt-python
      - libguestfs-tools
      - virt-install
      - bridge-utils
      - virt-manager
      - xorg-x11-xauth
      - liberation-sans-fonts

    - name: Libvirt enable
      service: name=libvirtd enabled=yes

    - name: Libvirt started
      service: name=libvirtd state=started

    - name: Configure Image Pool 1
      command: bash -c "virsh pool-define-as images dir - - - - "/home""

    - name: Configure Image Pool 2
      command: bash -c "virsh pool-build images"

    - name: Configure Image Pool 3
      command: bash -c "virsh pool-start images"

    - name: Configure Image Pool 4
      command: bash -c "virsh pool-autostart images"

    - name: Copy ifcfg-br0 to /etc/sysconfig/network-scripts/
      copy: src=ifcfg-br0 dest=/etc/sysconfig/network-scripts/ifcfg-br0 seuser=system_u

    - name: Copy ifcfg-enp1s000 to /etc/sysconfig/network-scripts/
      copy: src=ifcfg-enp1s000 dest=/etc/sysconfig/network-scripts/ifcfg-enp1s000 seuser=system_u

    - name: Switch On packet forwarding 1
      lineinfile:
          dest: /etc/sysctl.d/99-ipforward.conf
          line: net.ipv4.ip_forward = 1
          state: present
          create: yes

    - name: Switch On packet forwarding 2
      command: bash -c "sysctl -p /etc/sysctl.d/99-ipforward.conf"

    - name: Configure SSHD for virt-manager. Insert string 1
      lineinfile: 
        dest: /root/.bashrc
        line: X11DisplayOffset 10
        state: present
        create: yes

    - name: Configure SSHD for virt-manager. Insert string 1
      lineinfile: 
        dest: /root/.bashrc
        line: X11UseLocalhost yes
        state: present
        create: yes