---
- name: Run show commands on routers
  hosts: cisco
  gather_facts: false

  tasks:
   - name: run sh ip int br        
     raw: sh ip int br | ex unass
            
   - name: run sh ip route
     raw: sh ip route
     