---
- hosts: centos_group
  remote_user: root

  tasks:
  - name: add zabbix repository
    yum: name=http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm state=present

  - name: install zabbix-agent
    command: bash -c "yum -y install zabbix-agent"

  - name: copy zabbix configuration file
    copy: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf seuser=system_u

  - name: restart zabbix-agent
    command: bash -c "systemctl restart zabbix-agent"

  - name: enable zabbix-agent
    command: systemctl enable zabbix-agent


